add button, aligment content
glebhg/todo pull request #6
Opened 2021-06-24 13:11 UTC by cornhubius

добавил кнопку и сделал отступы

2021-06-28 13:46 UTC, glebhg requested changes

2021-06-28 13:46 UTC, glebhg commented on corn/index.html
> +  <!-link rel="stylesheet" href="styles.black.css" -->
```suggestion
  <!--link rel="stylesheet" href="styles.black.css" -->
```

2021-06-28 13:46 UTC, glebhg commented on corn/styles.css
> +}
I guess you don't need so many custom properties.

2021-06-28 13:46 UTC, glebhg commented on corn/styles.css
> +:root {
Looks like it positioned wrongly:

![Screenshot 2021-06-28 at 16 42 21](https://user-images.githubusercontent.com/84386984/123646887-4ace5c80-d830-11eb-97be-2df894dfcc9e.png)

2021-06-30 20:29 UTC, glebhg requested changes

2021-06-30 20:29 UTC, glebhg commented on corn/styles.css
> +}
You just need here properties that you will override in `styles.black.css`

2021-07-06 09:43 UTC, yogahub reviewed
All fixed....

2021-07-07 17:42 UTC, closed without merging